name: qa-bot

services:
  bot:
    container_name: qa-bot
    build:
      context: .
    image: qa-bot
    restart: on-failure:5
    volumes:
      - ./data:/data
      - ./secrets:/secrets
      - ./run:/run
