name: template-bot

services:
  db:
    container_name: template-db
    image: postgres:16
    restart: on-failure:5
    ports:
      - '8080:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - ./data:/var/lib/postgresql/data

  cache:
    container_name: template-bot-redis
    image: redis:7.2.1
    restart: on-failure:5
    expose:
      - '6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./cache:/data

  bot:
    container_name: template-bot
    build:
      context: .
    image: template-bot
    restart: on-failure:5
    depends_on:
      - db
      - cache
    links:
      - db
      - cache
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:postgres@db:5432/main"
      REDIS_URL: "redis://cache:6379/0"
    volumes:
      - ./secrets:/secrets
      - ./run:/run
